language: ruby
rvm:
  - 2.3.1

script:
  - bundle install
  - bundle exec rake

notifications:
  email:
    recipients:
      - wheresmybus@u.washington.edu
    on_success: change
    on_failure: change
